version: 0.2

env:
  shell: bash
  secrets-manager:
    DB_CONNECTION_STRING: test/dbConnectionString:dbConnectionString

phases:
  pre_build:
    on-failure: ABORT
    commands:
      - ./scripts/bootstrap.sh
  build:
    on-failure: ABORT
    commands:
      - ./scripts/build.sh
